### ISSUE TITLE
process_VSResults.py

### ISSUE THREAD

**Issue by subject-am** [MolecularFlipbook/FlipbookApp#3]
Hello,
I've been getting used to take advantage of these scripts available with Autodock Tools and until trying to use this one.

I wonder if you could help me with this error.
Thank you in advance for the time you spend on this!

`[user@server]$ pythonsh process_VSResults.py -d ./ -r ./receptor.pdbqt -D -p -v`
```
setting PYTHONHOME environment
set verbose to  True
Traceback (most recent call last):
  File "/.../mgltools_x86_64Linux2_1.5.6/MGLToolsPckgs/AutoDockTools/Utilities24/process_VSResults.py", line 209, in <module>
    drp.process(directory, verbose=verbose)
  File "/.../mgltools_x86_64Linux2_1.5.6/MGLToolsPckgs/Updates/nightly_2013_06_07/AutoDockTools/Docking.py", line 1466, in process
    dlg_list = glob.glob(os.path.join(directory, "*.dlg"))
AttributeError: 'function' object has no attribute 'glob'

**Comment by ddh-viva** [comment]
Hi, hope this helps.
http://autodock.scripps.edu/faqs-help/faq/is-there-a-way-to-save-a-protein-ligand-complex-as-a-pdb-file-in-autodock
Also you may replace 
`dlg_list = glob.glob(os.path.join(directory, "*.dlg"))`
with  
`dlg_list = glob(os.path.join(directory, "*.dlg"))`
and try again.
